### PR TITLE
example R: fix the list formatting

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 204 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2gRTZC_k_PKdXlY_u:-Mo2gRTZC_k_PKdXlY_v:bbe0tfn) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L204)):*
> ```
> system.
> ```

`system,`
___
*[templates/examples/R/body.tmpl, line 208 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2gfLbBLBheIg7-JuP:-Mo2gfLbBLBheIg7-JuQ:bbe0tfn) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L208)):*
> ```
> system.
> ```

`system,`
___
*[templates/examples/R/body.tmpl, line 211 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2gilH2LRLPknrKY9x:-Mo2gilH2LRLPknrKY9y:b-28crtj) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L211)):*
> ```
> architectures.
> ```

`architectures,`
___
*[templates/examples/R/body.tmpl, line 212 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2glo9DXKDShCOsjPe:-Mo2glo9DXKDShCOsjPf:bj4wy0m) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L212)):*
> ```
> The
> ```

`the` (please revert) - it is not a full sentence, but an element of the list. The previous list elements starts with a capital letters, because they start with a "own name" or a shortcut of it.

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 204 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2gRTZC_k_PKdXlY_u:-Mo2smQM9EWB8xfl_G8g:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L204)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> system.
> ```

`system,`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 208 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2gfLbBLBheIg7-JuP:-Mo2sqU72zIKKwlQdur3:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L208)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> system.
> ```

`system,`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 211 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2gilH2LRLPknrKY9x:-Mo2st8B8_S6jQC7bRl-:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L211)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> architectures.
> ```

`architectures,`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 212 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-Mo2glo9DXKDShCOsjPe:-Mo2sx9xEgCrs8iuf9br:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/3566803a0edd0ebccb2f2eea5261c8ebc913c1f1/templates/examples/R/body.tmpl#L212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The
> ```

`the` (please revert) - it is not a full sentence, but an element of the list. The previous list elements starts with a capital letters, because they start with a "own name" or a shortcut of it.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-:-Mo2uZ8V1-7dboSf6llN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25#-:-Mo2vgGqAgedFIsk2_4u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
