### PR TITLE
example R: configure SoftRoCE

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/3)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/3)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/3#-MkfypWtDmoMx5Gvnvs0:-MkfypWtDmoMx5Gvnvs1:b-wdjwsq) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2c8e8c7d3c758538fc982773169adec00f29ee32/scripts/enable_pmemusers#L108)):*
> ```
> my $ip = `./scripts/config_softroce.sh`;
> ```

add error handling ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/3)* status: 0 of 3 files reviewed, all discussions resolved

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/3#-MkfypWtDmoMx5Gvnvs0:-Mkg9bQeDjEbu-t1pMx3:bb6un1j) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2c8e8c7d3c758538fc982773169adec00f29ee32/scripts/enable_pmemusers#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> my $ip = `./scripts/config_softroce.sh`;
> ```

add error handling ?
</blockquote></details>

Done

**Comment by ldorau** [comment]
@janekmi @osalyk @grom72 please review

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/3#-:-Mkgoik302ZK8V7iLLBr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/3#-Mkgoj0r6eWb4QlXojuA:-Mkgoj0r6eWb4QlXojuB:bp4hmwj) (no related file):*
FYI It works on my side!

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/3#-:-Mkl9stj7an7o-wd6vJ1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
