### PR TITLE
example R: name the main example

### PR DESCRIPTION
**Pull request by ldorau**
Set the name of the main example to "main".

See: https://github.com/ldorau/2021-04-21/pull/19

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/6)

### CODE REVIEW

**Comment by ldorau** [comment]
@janekmi @osalyk @grom72 please review

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/6#-:-MklW6sO58bg5DbDNOu-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/6#-:-Mkl_4fG0f55owakrvdM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
