### PR TITLE
example R: fix running docker in enable_pmemusers()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/34)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/34)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`scripts/enable_pmemusers` line 135 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/34#-NBWFhY7-bJ_fn99GIpN:-NBWFhY7-bJ_fn99GIpO:by6t7bp) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/1223870a8652df9dec531941ca579a16ccbed942/scripts/enable_pmemusers#L135)):*
> ```
> 		say("WARNING: config_softroce.sh failed, SoftRoCE is not configured, the Example R will not work!");
> 		$ip = "config_softroce.sh_failed";
> 		runy("docker run -t -d --name=$user --env RPMA_SOFT_ROCE_IP=$ip --env PMEMUSER_ID=$id --env DEV_DAX=$dev_dax -v $H/users/$user/shadow:/etc/shadow -v $H/users/$user/passwd:/etc/passwd -v $H/users/$user/group:/etc/group -v $H/users/$user/home:/home/$user -v $pmemdir:/pmem -u $thisid:$thisid --hostname=container$id --workdir=/home/$user --cap-add SYS_PTRACE --restart=unless-stopped $Image");
> ```

Do we need this option if Example R is not used?



_Code quote:_
```
--env RPMA_SOFT_ROCE_IP=$ip
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/34)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`scripts/enable_pmemusers` line 135 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/34#-NBWFhY7-bJ_fn99GIpN:-NBWJ40t4IA4otChjzRA:bxn96y2) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/1223870a8652df9dec531941ca579a16ccbed942/scripts/enable_pmemusers#L135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this option if Example R is not used?
</blockquote></details>

Yes, in case someone starts Example R - it would pass the error message.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/34#-:-NBWKhu0CU1e4F0LFgcn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
