### PR TITLE
example R: add details to the outline

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 9 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-Mn0Eb5D0PmuvBZajHNR:-Mn0Eb5D0PmuvBZajHNS:bhr08h1) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5ec5488be51cf9af19306b8be254d7723cd5e2d9/templates/examples/R/body.tmpl#L9)):*
> ```
> - expected outcomes for the trainee
> - what the trainee will do during this tutorial (high-level)?
> ```

Reverse order:
```
- what the trainee will do during this tutorial (high-level)?
- expected outcomes for the trainee
```

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-:-Mn-ZHfi3Xtxtwgimoy1:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 9 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-Mn0Eb5D0PmuvBZajHNR:-Mn0h1oc0idblAI1sTue:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5ec5488be51cf9af19306b8be254d7723cd5e2d9/templates/examples/R/body.tmpl#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> - expected outcomes for the trainee
> - what the trainee will do during this tutorial (high-level)?
> ```

Reverse order:
```
- what the trainee will do during this tutorial (high-level)?
- expected outcomes for the trainee
```
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-:-Mn0hXUN7rhARoFg-c4f:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-:-Mn0nf5r4DcdSXCBTVjh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Comment by Patryk717** [comment]
___
*[templates/examples/R/body.tmpl, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-Mn0niZN5q1fqzZrTZTl:-Mn0niZN5q1fqzZrTZTm:b-vimimy) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5fa26c01fd9ceac2307cdc9a27127095f4d4ebc3/templates/examples/R/body.tmpl#L11)):*
> ```
> <p>
> XXX
> - briefly what hardware and software components are required
> ```

why deleted this line?
we cannot write at the very top the things we need "software components are required"

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/10)* status: all files reviewed, 1 unresolved discussion

___
*[templates/examples/R/body.tmpl, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-Mn0niZN5q1fqzZrTZTl:-Mn0xOuyDiBttPetZJGD:bcdd77b) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5fa26c01fd9ceac2307cdc9a27127095f4d4ebc3/templates/examples/R/body.tmpl#L11)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

why deleted this line?
we cannot write at the very top the things we need "software components are required"
</blockquote></details>

It was moved down to the 'Connectivity check' step.

I'm not sure which approach will be more comprehensible. Right now my thinking is:

1. Explain what we are doing here. (Instead of loading the reader with what he needs to buy and install).
2. Introduce required hardware and software components along the way.

But, I'm open to reviewing my approach when we will be closer to the final revision. Keep this thought.

**Comment by Patryk717** [comment]
___
*[templates/examples/R/body.tmpl, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-Mn0niZN5q1fqzZrTZTl:-Mn519ez5JqN-dxb1own:b-6cv8w4) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5fa26c01fd9ceac2307cdc9a27127095f4d4ebc3/templates/examples/R/body.tmpl#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It was moved down to the 'Connectivity check' step.

I'm not sure which approach will be more comprehensible. Right now my thinking is:

1. Explain what we are doing here. (Instead of loading the reader with what he needs to buy and install).
2. Introduce required hardware and software components along the way.

But, I'm open to reviewing my approach when we will be closer to the final revision. Keep this thought.
</blockquote></details>

in my opinion, I would prefer everything I need to install to be given at the top,
it will enable me not to be distracted by the task, "because I don't have something"

**Comment by Patryk717** [comment]
___
*[templates/examples/R/body.tmpl, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/10#-Mn0niZN5q1fqzZrTZTl:-Mn52XZA8ZKUIZPAEVYN:bmkqkke) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5fa26c01fd9ceac2307cdc9a27127095f4d4ebc3/templates/examples/R/body.tmpl#L11)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

in my opinion, I would prefer everything I need to install to be given at the top,
it will enable me not to be distracted by the task, "because I don't have something"
</blockquote></details>

but okay, we'll see what happens next

**Comment by Patryk717** [comment]
:lgtm:

**Pull request merged**
