### PR TITLE
example R: language fixes

### PR DESCRIPTION
**Pull request by ldorau**
Some language fixes:
- fix incorrect use of "In this step",
- replace "we" with "you" where appropriate

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/26)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/26#-:-Mo2vupYEj_Fff_dOnzS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/26)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 99 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/26#-Mo2ymUT7U6Muon_9h9-:-Mo2ymUT7U6Muon_9h90:b-8dwgy5) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/b0fff140c10fa5a8f20d0c7e2715935bd6f75173/templates/examples/R/body.tmpl#L99)):*
> ```
> 
> <p>
> You will implement both sides of an RDMA connection now:
> ```

I don't like putting "now" at the end of all of these sentences. Especially in front of a list. I have tried to learn how "now" in sentences can be used. I didn't find anything like this that you have proposed. What do you think?

Ref: https://sentence.yourdictionary.com/now

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/26)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 99 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/26#-Mo2ymUT7U6Muon_9h9-:-Mo32OsO5FNogd4rEaZq:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/b0fff140c10fa5a8f20d0c7e2715935bd6f75173/templates/examples/R/body.tmpl#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like putting "now" at the end of all of these sentences. Especially in front of a list. I have tried to learn how "now" in sentences can be used. I didn't find anything like this that you have proposed. What do you think?

Ref: https://sentence.yourdictionary.com/now
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/26#-:-Mo3VdfeEep3yDwHJmbd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/26#-:-Mo3_FBF9PqAZhfMQ1SS:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
