### PR TITLE
example R: verify parameters of device DAX

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[scripts/enable_pmemusers, line 103 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0hlcBBJQ6t9Thcrgm:-Mn0hlcBBJQ6t9Thcrgn:b-pcljwz) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L103)):*
> ```
> 
> # look for device DAX in ndctl
> my $exists = `ndctl list | grep -e "$dax_name" | wc -l`;
> ```

`grep -c ...`
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0iBAO0afkgJSpSSdo:-Mn0iBAO0afkgJSpSSdp:b-vr2c5o) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
> ```
> die "$dev_dax device DAX not listed by ndctl\n" if ($exists != 1);
> 
> # minimum required size of device DAX is 800 kB (4kB per user)
> ```

the minimum...
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0km012aVxbMI3DE86:-Mn0km012aVxbMI3DE87:b-6mxgia) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
> ```
> die "$dev_dax device DAX not listed by ndctl\n" if ($exists != 1);
> 
> # minimum required size of device DAX is 800 kB (4kB per user)
> ```

4**KiB** for each of 200 users
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0l45AAU-itpALXg0N:-Mn0l45AAU-itpALXg0O:bpj1ogh) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
> ```
> die "$dev_dax device DAX not listed by ndctl\n" if ($exists != 1);
> 
> # minimum required size of device DAX is 800 kB (4kB per user)
> ```

800**KiB**
___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0jggR4_e2cwjV454C:-Mn0jggR4_e2cwjV454D:b-zlydj) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L108)):*
> ```
> 
> # minimum required size of device DAX is 800 kB (4kB per user)
> my $size = `ndctl list | grep -B2 -e "$dax_name" | grep size | cut -d: -f2 | cut -d, -f1 | cut -d'"' -f2`;
> ```

In my opinion, it is not a very maintainable way of processing JSON. Leaving alone its readability.
I propose an alternative:

```sh
ndctl list | jq ".[] | select(.chardev==\"$dev_dax\")" | jq '.size'
```

Pros:

- readability
- maintainability

Cons:

- jq(1) is required in the system

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0jggR4_e2cwjV454C:-Mn0pS_6BPlcWKyOjIyZ:b5zv10r) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In my opinion, it is not a very maintainable way of processing JSON. Leaving alone its readability.
I propose an alternative:

```sh
ndctl list | jq ".[] | select(.chardev==\"$dev_dax\")" | jq '.size'
```

Pros:

- readability
- maintainability

Cons:

- jq(1) is required in the system
</blockquote></details>

It produces the empty output on Fedora 31:

```
$ sudo ndctl list 
[
  {
    "dev":"namespace0.0",
    "mode":"devdax",
    "map":"dev",
    "size":1054867456,
    "uuid":"3fbcf450-cb83-4cf6-914b-5653a2caff2f",
    "chardev":"dax0.0",
    "align":2097152
  }
]
$ sudo ndctl list | jq ".[] | select(.chardev==\"$dev_dax\")" | jq '.size'
$ sudo ndctl list | jq ".[] | select(.chardev==\"$dev_dax\")"
$

```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[scripts/enable_pmemusers, line 103 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0hlcBBJQ6t9Thcrgm:-Mn0qKJMAShPW3zaYpV8:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`grep -c ...`
</blockquote></details>

Done.
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0iBAO0afkgJSpSSdo:-Mn0qKe6DnZnLPKcK0eI:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the minimum...
</blockquote></details>

Done.
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0km012aVxbMI3DE86:-Mn0qPwb8f_giow5AKjn:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

4**KiB** for each of 200 users
</blockquote></details>

Done.
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0l45AAU-itpALXg0N:-Mn0qQKHBIpBb-716gu0:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

800**KiB**
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0km012aVxbMI3DE86:-Mn0vrl-7JiRcxCNN5TW:b3krq) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

K
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0l45AAU-itpALXg0N:-Mn0vtbL16pUx8dIwMjD:b3krq) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

K
___
*[scripts/enable_pmemusers, line 103 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0wkIS30ZQtQK4tfbi:-Mn0wkIS30ZQtQK4tfbj:b1e5hm7) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/4262c4352b103bf81ab6e5a8d41345d7955b44ba/scripts/enable_pmemusers#L103)):*
> ```
> 
> # look for device DAX in ndctl
> my $exists = `ndctl list | grep -c -e "$dax_name"`;
> ```

What is `-e` for?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0km012aVxbMI3DE86:-Mn100Ku9YsKsCWYAQEl:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

K
</blockquote></details>

Done.
___
*[scripts/enable_pmemusers, line 107 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0l45AAU-itpALXg0N:-Mn100yUDvyjUdqW3xzm:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

K
</blockquote></details>

Done.
___
*[scripts/enable_pmemusers, line 103 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0wkIS30ZQtQK4tfbi:-Mn1-i7e3qiArQ6oD6qJ:b-qwgvft) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/4262c4352b103bf81ab6e5a8d41345d7955b44ba/scripts/enable_pmemusers#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is `-e` for?
</blockquote></details>

From grep(1):
```
   Matching Control
       -e PATTERNS, --regexp=PATTERNS
              Use PATTERNS as the patterns.
```

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[scripts/enable_pmemusers, line 103 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0wkIS30ZQtQK4tfbi:-Mn1D-mSA7qG1vZdwHmx:bc72jdd) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/4262c4352b103bf81ab6e5a8d41345d7955b44ba/scripts/enable_pmemusers#L103)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

From grep(1):
```
   Matching Control
       -e PATTERNS, --regexp=PATTERNS
              Use PATTERNS as the patterns.
```

</blockquote></details>

Yeah. Being explicit: why you think it is needed here?
___
*[scripts/enable_pmemusers, line 107 at r3](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn1D8MHCOALEf-sSdKC:-Mn1D8MIATKDOUGRwlSi:b8pqgmu) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/221865dbdafc7b76a7f41a1614b5aafbbb76da2a/scripts/enable_pmemusers#L107)):*
> ```
> die "$dev_dax device DAX not listed by ndctl\n" if ($exists != 1);
> 
> # the minimum required size of device DAX is 800 KiB (4KiB per user)
> ```

Space is not needed between '800' and 'KiB'.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0jggR4_e2cwjV454C:-Mn1FaVK9FJ6gyn-H0v-:b-28gyhg) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It produces the empty output on Fedora 31:

```
$ sudo ndctl list 
[
  {
    "dev":"namespace0.0",
    "mode":"devdax",
    "map":"dev",
    "size":1054867456,
    "uuid":"3fbcf450-cb83-4cf6-914b-5653a2caff2f",
    "chardev":"dax0.0",
    "align":2097152
  }
]
$ sudo ndctl list | jq ".[] | select(.chardev==\"$dev_dax\")" | jq '.size'
$ sudo ndctl list | jq ".[] | select(.chardev==\"$dev_dax\")"
$

```
</blockquote></details>

I will retry with $dev_dax set tomorrow ;-))
___
*[scripts/enable_pmemusers, line 103 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0wkIS30ZQtQK4tfbi:-Mn1FoaQD0bRouh1iIeF:b-rnqb7v) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/4262c4352b103bf81ab6e5a8d41345d7955b44ba/scripts/enable_pmemusers#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah. Being explicit: why you think it is needed here?
</blockquote></details>

Maybe it is not required here, but I think it is safer to always use `-e` before the pattern.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0jggR4_e2cwjV454C:-Mn4RnQjAadWwA3XThGV:bp1ubcx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I will retry with $dev_dax set tomorrow ;-))
</blockquote></details>

Yeah, but `jq` is required on the host system, what we cannot guarantee ...
___
*[scripts/enable_pmemusers, line 107 at r3](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn1D8MHCOALEf-sSdKC:-Mn4RSq_2YY_b9Y2yXhw:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/221865dbdafc7b76a7f41a1614b5aafbbb76da2a/scripts/enable_pmemusers#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Space is not needed between '800' and 'KiB'.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0jggR4_e2cwjV454C:-Mn4sRH17jh2qfBZAg7m:b-7wvx50) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yeah, but `jq` is required on the host system, what we cannot guarantee ...
</blockquote></details>

Yeah. We cannot. But we can force the user to have tools required to process the output format which is forced on us to consume. ;-)

Please see the comment above.
___
*[scripts/enable_pmemusers, line 87 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn4pcF5EGSEKCntSUAG:-Mn4pcF5EGSEKCntSUAH:b8zi7ej) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/b40ee45f217e586b1916801f786fd76cff71eb9c/scripts/enable_pmemusers#L87)):*
> ```
> die "$H/js directory not found\n" unless -d "$H/js";
> die "$H/templates directory not found\n" unless -d "$H/templates";
> die "$H/users directory not found\n" unless -d "$H/users";
> ```

```perl
die "the jq command is missing\n" unless system("which jq") == 0
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[scripts/enable_pmemusers, line 108 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn0jggR4_e2cwjV454C:-Mn5IivO1naw7-gtddHx:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/80db64603cded24a9020d60751b01e7875284a3f/scripts/enable_pmemusers#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah. We cannot. But we can force the user to have tools required to process the output format which is forced on us to consume. ;-)

Please see the comment above.
</blockquote></details>

Done.
___
*[scripts/enable_pmemusers, line 87 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn4pcF5EGSEKCntSUAG:-Mn5IeoD5rJDkN_LQbXp:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/b40ee45f217e586b1916801f786fd76cff71eb9c/scripts/enable_pmemusers#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```perl
die "the jq command is missing\n" unless system("which jq") == 0
```
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[scripts/enable_pmemusers, line 88 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn5McchCuAgN92jZtNW:-Mn5McchCuAgN92jZtNX:brq3klk) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/c28bd87f9f9925efbc52e4a1ede34032b1c1e59e/scripts/enable_pmemusers#L88)):*
> ```
> die "$H/templates directory not found\n" unless -d "$H/templates";
> die "$H/users directory not found\n" unless -d "$H/users";
> die "the jq command is missing\n" unless system("which jq") == 0;
> ```

I recommend adding `> /dev/null`. It looks ugly in the output.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[scripts/enable_pmemusers, line 88 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-Mn5McchCuAgN92jZtNW:-Mn5NuRBCphPcRRjpWZt:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/c28bd87f9f9925efbc52e4a1ede34032b1c1e59e/scripts/enable_pmemusers#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend adding `> /dev/null`. It looks ugly in the output.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-:-Mn5O3XW2a9uSOzUpb3p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/11#-:-Mn5j5f6A_o_1cltL_oZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
