### PR TITLE
scripts: remove --privileged

### PR DESCRIPTION
**Pull request by janekmi**
Instead fix a way the access is given to the /dev/infiniband device.

Ref: #3

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/8)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/8#-:-MlFswtZAo47W0gtHSiv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
It works :+1: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/8#-:-MlJLuWLE2myZLat0apl:b-gon65k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/8#-:-MlOofncDpJatvvo79UV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
