### PR TITLE
example R: establishing a connection

### PR DESCRIPTION
**Pull request by osalyk**
- [x] add schema

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna-azwCUDQq4ThcwB4:-Mna-azwCUDQq4ThcwB5:btkxf5r) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
> ```
> Library
> ```

library
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna-qhpB_Wg2tcJ3YQt:-Mna-qhpB_Wg2tcJ3YQu:bdegcm7) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
> ```
> information, see
> ```

`information see` - no comma in between please
___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna0ii9CXcd4xTO8KKq:-Mna0ii9CXcd4xTO8KKr:b-ccqb61) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
> ```
> two parts of the connection establishing process
> ```

A server and a client are not parts of the "connection establishing process".

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna0ii9CXcd4xTO8KKq:-MnaIdyG9yY1uE6qa58a:bxj8ok6) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> two parts of the connection establishing process
> ```

A server and a client are not parts of the "connection establishing process".
</blockquote></details>

Maybe:

`This example implements two sides of an RDMA connection:`

? 
@janekmi what do you think? Maybe you have a better idea?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna-azwCUDQq4ThcwB4:-MnaAlBlAsD_0y2B7Sfq:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Library
> ```

library
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna-qhpB_Wg2tcJ3YQt:-MnaAnlCC8tkSJievdh5:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> information, see
> ```

`information see` - no comma in between please
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna0ii9CXcd4xTO8KKq:-Mne1Lcp9MiZ2hLYB0i6:b8eau52) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe:

`This example implements two sides of an RDMA connection:`

? 
@janekmi what do you think? Maybe you have a better idea?
</blockquote></details>

I like it.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndxT-j8S-KFAb7Et-4:-MndxT-j8S-KFAb7Et-5:b-bdyxue) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
> ... library (librpma)...

instead of 

> ~~(RPMA)~~
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndxsC49MeAYdC1jdKx:-MndxsC49MeAYdC1jdKy:b9bgxn3) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
> ```
> 
> <p>
> The Remote Persistent Memory Access (RPMA) Library is a C library to simplify accessing persistent memory on remote hosts over Remote Direct Memory Access (RDMA). For more information, see <a href="https://pmem.io/rpma/" target="_blank">pmem.io</a>.
> ```

... persistent memory... -> PMem
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mndxxdg8-p_dE51e_Lp:-Mndxxdg8-p_dE51e_Lq:bskde7v) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
> ```
> 
> <p>
> The Remote Persistent Memory Access (RPMA) Library is a C library to simplify accessing persistent memory on remote hosts over Remote Direct Memory Access (RDMA). For more information, see <a href="https://pmem.io/rpma/" target="_blank">pmem.io</a>.
> ```

In this document, we have started using 'systems' instead of 'hosts'.
I recommend following this schema.
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndyRPG-7BKMoQOtH2r:-MndyJRe8F6djuiLsyev:bgjfm7l) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
> RDMA.

instead of

> ... Remote Direct Memory Access (RDMA).

It is already introduced.
___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna0ii9CXcd4xTO8KKq:-Mndz9SO38JPNo4EqLUJ:b-22lm4g) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe:

`This example implements two sides of an RDMA connection:`

? 
@janekmi what do you think? Maybe you have a better idea?
</blockquote></details>

... both sides... :+1: 
___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndzHdT8qn9KiVVp_9y:-MndzHdT8qn9KiVVp_9z:bp53ji5) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
> The applications below implement...

instead of

> This example implements...

? I don't like the naming schema of the hackathon framework overall but it calls this page an example. So, naming the following part as an example we have a name conflict. ;-)
___
*[templates/examples/R/body.tmpl, line 87 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mne5TGOBUtcTvQNg4-D:-Mne5TGOBUtcTvQNg4-E:b-90u656) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/de067544c66a3dd218f241e3085214dbbdad8386/templates/examples/R/body.tmpl#L87)):*
> ```
> This example implements two sides of an RDMA connection:
> <ul>
>     <li>a server which will be waiting for incoming connections using single RPMA endpoint (see the <a href="https://pmem.io/rpma/manpages/master/librpma.7.html#server-operation" target="_blank">server operation documentation</a> for details).</li>
> ```

a server that waits for incoming connections using a single endpoint
___
*[templates/examples/R/body.tmpl, line 88 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mne5mCp73olrgxEo4jL:-Mne5mCp73olrgxEo4jM:biraowa) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/de067544c66a3dd218f241e3085214dbbdad8386/templates/examples/R/body.tmpl#L88)):*
> ```
> <ul>
>     <li>a server which will be waiting for incoming connections using single RPMA endpoint (see the <a href="https://pmem.io/rpma/manpages/master/librpma.7.html#server-operation" target="_blank">server operation documentation</a> for details).</li>
>     <li>a client which will initiate establishing the connection to the server (see the <a href="https://pmem.io/rpma/manpages/master/librpma.7.html#client-operation" target="_blank">client operation documentation</a> for details)</li>
> ```

a client which attempts to establish the connection to the server

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndzHdT8qn9KiVVp_9y:-Mne71Og1TUiiRgpAAnW:b-j86s72) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
Or:

> In this step, you will implement...

?
___
*[templates/examples/R/body.tmpl, line 89 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mne60pT55_gp0DJns4Q:-Mne5pae6_8ETKGvQHQt:b-2n4dbk) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/de067544c66a3dd218f241e3085214dbbdad8386/templates/examples/R/body.tmpl#L89)):*
I think about adding here a paragraph saying why we are doing so "little" in these applications e.g.

> These applications are intentionally doing no more than connection and disconnection to familiarize you with the process. Building on this you will do more in the next step.

What do you think?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndxT-j8S-KFAb7Et-4:-Mne8GDz-mxTYSx6BRZF:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ... library (librpma)...

instead of 

> ~~(RPMA)~~
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndxsC49MeAYdC1jdKx:-Mne8Lmn4CgvVkamwyIG:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... persistent memory... -> PMem
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mndxxdg8-p_dE51e_Lp:-Mne8a836q-hKDX9zRIm:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In this document, we have started using 'systems' instead of 'hosts'.
I recommend following this schema.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 64 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndyRPG-7BKMoQOtH2r:-Mne8tSM40w14HXj4YJX:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> RDMA.

instead of

> ... Remote Direct Memory Access (RDMA).

It is already introduced.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mna0ii9CXcd4xTO8KKq:-Mne8yGs8g8mdeX6Fk4c:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... both sides... :+1: 
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 70 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MndzHdT8qn9KiVVp_9y:-Mne9DbR7_A1bzJYWYSD:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/35e8f09904be58986867914e156abba0c4828367/templates/examples/R/body.tmpl#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Or:

> In this step, you will implement...

?
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 87 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mne5TGOBUtcTvQNg4-D:-Mne9QDcCr51-zyw_oLG:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/de067544c66a3dd218f241e3085214dbbdad8386/templates/examples/R/body.tmpl#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a server that waits for incoming connections using a single endpoint
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 88 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mne5mCp73olrgxEo4jL:-Mne9VYr-3tSBIH1Zd50:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/de067544c66a3dd218f241e3085214dbbdad8386/templates/examples/R/body.tmpl#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a client which attempts to establish the connection to the server
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 89 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mne60pT55_gp0DJns4Q:-MneA7rM3kxUVFDeB2V5:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/de067544c66a3dd218f241e3085214dbbdad8386/templates/examples/R/body.tmpl#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think about adding here a paragraph saying why we are doing so "little" in these applications e.g.

> These applications are intentionally doing no more than connection and disconnection to familiarize you with the process. Building on this you will do more in the next step.

What do you think?
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[img/examples/R/schema.jpg, line 0 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MneMEM09P0sanALW5xd:-MneMEM09P0sanALW5xe:b-elfum0) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/c6a5913f81f7632f09da50c82a83a8103d269560/img/examples/R/schema.jpg#L0)):*
I don't like the name. (The software developer's classic complaint. xD)
Schema sounds too unspecific. I am thinking more about the ecosystem or something similar.
Any ideas?

**Review by Patryk717 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-:-MneOotI9GSrVD6a2bDi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[img/examples/R/schema.jpg, line  at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MneMEM09P0sanALW5xd:-MneP-q1-UIgrhlRM495:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/c6a5913f81f7632f09da50c82a83a8103d269560/img/examples/R/schema.jpg#L)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like the name. (The software developer's classic complaint. xD)
Schema sounds too unspecific. I am thinking more about the ecosystem or something similar.
Any ideas?
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-:-MnejrD9A1SNKl5unNUL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 92 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MnexNU88bqEybSML7Vu:-MnexNU88bqEybSML7Vv:b-s88xqs) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/e8173e6af1102b16aa0aa512697f2470895b89db/templates/examples/R/body.tmpl#L92)):*
> ```
> These applications are intentionally doing no more than connection and disconnection 
> ```

These applications intentionally do only connection and disconnection ...
___
*[templates/examples/R/body.tmpl, line 92 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnexh6vEpPnjlH4f34z:-Mnexh6vEpPnjlH4f35-:b-44gp2v) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/e8173e6af1102b16aa0aa512697f2470895b89db/templates/examples/R/body.tmpl#L92)):*
> ```
> to familiarize you with the process.
> ```

to familiarize you with these processes.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 92 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-MnexNU88bqEybSML7Vu:-MneyVif6xbNtirSKL0x:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/e8173e6af1102b16aa0aa512697f2470895b89db/templates/examples/R/body.tmpl#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> These applications are intentionally doing no more than connection and disconnection 
> ```

These applications intentionally do only connection and disconnection ...
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 92 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnexh6vEpPnjlH4f34z:-MneyagU3DTD1lUMch2k:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/e8173e6af1102b16aa0aa512697f2470895b89db/templates/examples/R/body.tmpl#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to familiarize you with the process.
> ```

to familiarize you with these processes.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-:-Mnf-nWp4_mikUhDbJHx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 82 at r6](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnf0mKrE4j2K6hEgnJI:-Mnf0mKrE4j2K6hEgnJJ:b5ng50b) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2a80731063d6e2d78511957b90d7b2b0eb218cb2/templates/examples/R/body.tmpl#L82)):*
> ```
> 
> ```

It does not work:

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 82 at r6](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnf0mKrE4j2K6hEgnJI:-Mnf4hiK9EvSi22JVy1w:bnt3q1j) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2a80731063d6e2d78511957b90d7b2b0eb218cb2/templates/examples/R/body.tmpl#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 
> ```

It does not work:



</blockquote></details>

Do images in other examples work properly?

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 82 at r6](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnf0mKrE4j2K6hEgnJI:-Mnf7Ix32RGlqbS5SJ5T:bg3xq5d) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2a80731063d6e2d78511957b90d7b2b0eb218cb2/templates/examples/R/body.tmpl#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do images in other examples work properly?
</blockquote></details>

Yes, they do.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 82 at r6](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnf0mKrE4j2K6hEgnJI:-MnfAgPD4cNgUh_-Qhvy:bdg9h28) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2a80731063d6e2d78511957b90d7b2b0eb218cb2/templates/examples/R/body.tmpl#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, they do.
</blockquote></details>

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 82 at r6](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnf0mKrE4j2K6hEgnJI:-MnfKg1G14uR09950Rf2:b-qsmngu) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2a80731063d6e2d78511957b90d7b2b0eb218cb2/templates/examples/R/body.tmpl#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>


</blockquote></details>

It works now, but the picture is far too big - it does not even fit into a page :-)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 82 at r6](https://reviewable.io/reviews/ldorau/2021-04-21.web/15#-Mnf0mKrE4j2K6hEgnJI:-MnfOHPYCKCHlTv6p7Vc:b-hotern) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/2a80731063d6e2d78511957b90d7b2b0eb218cb2/templates/examples/R/body.tmpl#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It works now, but the picture is far too big - it does not even fit into a page :-)



</blockquote></details>

It looks great now :-)

**Pull request merged**
