### PR TITLE
example R: break lines longer than 90 characters (with some exceptions)

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/17)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/17#-:-MniteCn-F99R4DAFeZM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
:goat: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/17#-:-MnjP_mh3jOYskZhYoz9:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 146 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/17#-MnjPAyb8WA5Utwdp-g1:-MnjPAyb8WA5Utwdp-g2:bo8v57k) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/53c8dc0dba2752f60085e6e4354a53d7f07a6fde/templates/examples/R/body.tmpl#L146)):*
> ```
> <p>
> In this example, after having established a connection (see the previous step for details),
> the client reads (using <code>rpma_read()</code>) an initial content of the server's memory
> ```

This line still can be broken easily at the 90 characters limit.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/17)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 146 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/17#-MnjPAyb8WA5Utwdp-g1:-MnjTZKy7JHmB55XwhyX:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/53c8dc0dba2752f60085e6e4354a53d7f07a6fde/templates/examples/R/body.tmpl#L146)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line still can be broken easily at the 90 characters limit.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/17#-:-MnjUAbB2rOI51clpghi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
