### PR TITLE
docker: install librpma in the docker image

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)

### CODE REVIEW

**Comment by ldorau** [comment]
@janekmi @osalyk @grom72 please review

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqvPT2ukW-FS_fMts:-MkgqvPT2ukW-FS_fMtt:bfiwywq) (no related file):*
**Question**: Have you done a complete docker image rebuild with all other components in place?

---
___
*[docker/Dockerfile, line 118 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqNA9B5fbjo-GO9oa:-MkgqNA9B5fbjo-GO9ob:b-p7ttti) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9f3cc432243fe98284b0c5a59fad09c41cdfce4d/docker/Dockerfile#L118)):*
> ```Dockerfile
> 
> COPY librpma.sh /
> RUN /librpma.sh
> ```

Knowing this `tz.sh` is something different than all other installation scripts I recommend putting these two new lines before the `tz.sh` lines.
___
*[docker/Dockerfile, line 120 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-Mkgq_tN18TgRKkf8GOV:-Mkgq_tN18TgRKkf8GOW:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9f3cc432243fe98284b0c5a59fad09c41cdfce4d/docker/Dockerfile#L120)):*
> ```Dockerfile
> RUN /librpma.sh
> 
> RUN rm /pmdk.sh /valgrind.sh /pmemobj-cpp.sh /pmemkv.sh /pmemkv-jni.sh /pmemkv-java.sh /pmemkv-python.sh /pmemkv-nodejs.sh /pmemkv-ruby.sh /memkind.sh /tz.sh /librpma.sh
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqvPT2ukW-FS_fMts:-Mkgt22p3YVtPgAQlzD9:bkc3l9v) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Question**: Have you done a complete docker image rebuild with all other components in place?
</blockquote></details>

Not yet ;-) 

---
___
*[docker/Dockerfile, line 118 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqNA9B5fbjo-GO9oa:-Mkgt0Ud9f2o1L_DWylK:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9f3cc432243fe98284b0c5a59fad09c41cdfce4d/docker/Dockerfile#L118)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Knowing this `tz.sh` is something different than all other installation scripts I recommend putting these two new lines before the `tz.sh` lines.
</blockquote></details>

Done.
___
*[docker/Dockerfile, line 120 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-Mkgq_tN18TgRKkf8GOV:-Mkgt0whEJGqrX-QCMPW:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9f3cc432243fe98284b0c5a59fad09c41cdfce4d/docker/Dockerfile#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:goat: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-:-Mki5INAEd_mIDCiuDp2:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqvPT2ukW-FS_fMts:-MkkAecy3Dsg8SBhfueD:b-rz88he) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet ;-) 
</blockquote></details>

The current image does not build, there is the following error when building `pmemkv-java`:
```
Step 19/32 : RUN /pmemkv-java.sh
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project pmemkv: There are test failures.
```

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqvPT2ukW-FS_fMts:-MkkIOR63HtTj24fBO0J:bklg1r0) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The current image does not build, there is the following error when building `pmemkv-java`:
```
Step 19/32 : RUN /pmemkv-java.sh
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project pmemkv: There are test failures.
```

</blockquote></details>

See: https://github.com/pmemhackathon/2021-04-21.web/issues/7

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqvPT2ukW-FS_fMts:-MkkdKO78CWqxCBkc2bU:bpxwh5v) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See: https://github.com/pmemhackathon/2021-04-21.web/issues/7
</blockquote></details>

:+1:  when the fix is applied the image builds including the librpma installation?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-MkgqvPT2ukW-FS_fMts:-MkkpGHtCpUQHJdBh1WY:b-1w2hxl) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1:  when the fix is applied the image builds including the librpma installation?
</blockquote></details>

It does now (after having added the `rdma-core-devel` package).

---

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-:-Mkku65U8Z2xWz5tzcgL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/4#-:-MklPxHZDmgduTmAqMx_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
