### PR TITLE
example R: describe step "Remote Persistent Memory access"

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-:-MndurAz6o7b1WqhcQIY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-:-MneR7oHB5JClISfJi8N:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 101 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnePFUZBowPMxV9MUgB:-MnePFUZBowPMxV9MUgC:bmrlzr4) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L101)):*
<details><summary><i alt="summary">Quoted 18 lines of code…</i></summary>

> ```
> - introduce used rpma_read/write/flush() operations and
> 
> 
> 
> 
> 
> - describe their role in achieving remote persistency
> - describe what the example does
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ```
</details>

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[templates/examples/R/body.tmpl, line 82 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneEGjW2NNWZdcCce4Y:-MneEGjW2NNWZdcCce4Z:b-arm4y2) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L82)):*
> ```
> In this step we will read and write back RPMem's content in the persistent way using the following librpma functions:
> <ul>
>     <li>rpma_read() - initiates transferring (reading) data from the remote memory to the local memory
> ```

`<code>rpma_read()</code>`
___
*[templates/examples/R/body.tmpl, line 84 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneENSf4RhC9ZCLlQFi:-MneENSgAT0o39OqgbVT:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L84)):*
> ```
>     <li>rpma_read() - initiates transferring (reading) data from the remote memory to the local memory
>         (see the <a href="https://pmem.io/rpma/manpages/master/rpma_read.3" target="_blank">rpma_read(3) manual</a> for details),</li>
>     <li>rpma_write() - initiates transferring (writing) data from the local memory to the remote memory
> ```

.
___
*[templates/examples/R/body.tmpl, line 86 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneEO2N4My3XVY1_O7b:-MneEO2N4My3XVY1_O7c:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L86)):*
> ```
>     <li>rpma_write() - initiates transferring (writing) data from the local memory to the remote memory
>         (see the <a href="https://pmem.io/rpma/manpages/master/rpma_write.3" target="_blank">rpma_write(3) manual</a> for details),</li>
>     <li>rpma_flush() - initiates finalizing a transfer of data to the remote memory,
> ```

.
___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGbhQ3N4KpE8s8keR:-MneGbhQ3N4KpE8s8keS:b-arm4y2) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
> ```
> 
> <p>
> In this example, after having established a connection, the client reads (using rpma_read())
> ```

`<code>rpma_read()</code>`
___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGf7YDHzYNRiNVuAu:-MneGf7Z95U7Z2nfu2HK:b-jsuxd3) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
> ```
> 
> <p>
> In this example, after having established a connection, the client reads (using rpma_read())
> ```

... a connection (see the previous step for details), ...
___
*[templates/examples/R/body.tmpl, line 94 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGqJJ3TbEeCnn_ga7:-MneGqJJ3TbEeCnn_ga8:bupu679) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L94)):*
> ```
> In this example, after having established a connection, the client reads (using rpma_read())
> an initial content of the server's memory (the string: "<i>The initial content of the server memory</i>"),
> then it writes (using rpma_write()) the new message ("<i>Hello world!</i>") to the server's memory
> ```

`<code>rpma_write()</code>`
___
*[templates/examples/R/body.tmpl, line 96 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGRV82ovpX0U3E-Bi:-MneGRV82ovpX0U3E-Bj:bc93oca) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L96)):*
> ```
> then it writes (using rpma_write()) the new message ("<i>Hello world!</i>") to the server's memory
> and finally it flushes the just written data down to the persistent domain or deep enough to make it visible
> on the remote node (if the first option is not available).
> ```

You have just started breaking the lines.
___
*[templates/examples/R/body.tmpl, line 101 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnePFUZBowPMxV9MUgB:-MneiHhs6vuAB7D3VCru:bpp0hh8) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L101)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

> ```
> - introduce used rpma_read/write/flush() operations and
> 
> 
> 
> 
> 
> - describe their role in achieving remote persistency
> - describe what the example does
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ```

</blockquote></details>

What do you ask for?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[templates/examples/R/body.tmpl, line 101 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnePFUZBowPMxV9MUgB:-MneiokmBP5lBgWkTou7:bkjnp1k) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What do you ask for?
</blockquote></details>

@osalyk what do you mean ?

**Comment by Patryk717** [comment]
___
*[templates/examples/R/body.tmpl, line 101 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnePFUZBowPMxV9MUgB:-MnejKGc8frm1uKah6pD:bw8ar6) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk what do you mean ?
</blockquote></details>

miss click , sorry

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[templates/examples/R/body.tmpl, line 87 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnekkOI7rp2X---AzEK:-MnekkOJ9gVSi5iXYQLS:bmyl2z8) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L87)):*
> ```
>         (see the <a href="https://pmem.io/rpma/manpages/master/rpma_write.3" target="_blank">rpma_write(3) manual</a> for details),</li>
>     <li>rpma_flush() - initiates finalizing a transfer of data to the remote memory,
>         it flushes data down to the persistent domain or deep enough to make it visible on the remote node
> ```

I think the example should be simplified to accommodate only the `RPMA_FLUSH_TYPE_PERSISTENT ` type of flush.
Consequently, only this case should be described here.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[templates/examples/R/body.tmpl, line 95 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-Mnel6ELEGGvNU9fO_W6:-Mnel6ELEGGvNU9fO_W7:b-ll3bwp) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L95)):*
> ```
> an initial content of the server's memory (the string: "<i>The initial content of the server memory</i>"),
> then it writes (using rpma_write()) the new message ("<i>Hello world!</i>") to the server's memory
> and finally it flushes the just written data down to the persistent domain or deep enough to make it visible
> ```

. only `RPMA_FLUSH_TYPE_PERSISTENT `.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[templates/examples/R/body.tmpl, line 101 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnePFUZBowPMxV9MUgB:-MnevemaB6U3GTTGYIIK:b-5sm0gu) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L101)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

miss click , sorry
</blockquote></details>

@patryk717 please resolve this issue

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 82 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneEGjW2NNWZdcCce4Y:-MneyotdAhjAsL1wQVhn:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`<code>rpma_read()</code>`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 84 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneENSf4RhC9ZCLlQFi:-MneypM_3Qo39PnCPsZU:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 86 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneEO2N4My3XVY1_O7b:-Mneypz7AIqnKKU55dye:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 87 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MnekkOI7rp2X---AzEK:-Mnezijc3HTQGqezpXA8:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the example should be simplified to accommodate only the `RPMA_FLUSH_TYPE_PERSISTENT ` type of flush.
Consequently, only this case should be described here.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGbhQ3N4KpE8s8keR:-Mnez4YE46zGlcMNtmyI:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`<code>rpma_read()</code>`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGf7YDHzYNRiNVuAu:-MnezyZ29awWyh-Z8UA9:bj66e3w) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... a connection (see the previous step for details), ...
</blockquote></details>

I still do not understand
___
*[templates/examples/R/body.tmpl, line 94 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGqJJ3TbEeCnn_ga7:-Mnez5Uu4lhsE2SK2fOw:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`<code>rpma_write()</code>`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 95 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-Mnel6ELEGGvNU9fO_W6:-Mnezn-rCWMNwAYoWSFY:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

. only `RPMA_FLUSH_TYPE_PERSISTENT `.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 96 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGRV82ovpX0U3E-Bi:-MnezAX53tmHdgWqUSn7:b8pei5l) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L96)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have just started breaking the lines.
</blockquote></details>

Yes, that's right.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGf7YDHzYNRiNVuAu:-Mnf0NWK5WMT0iWoC2H1:b-pq77br) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
Please add this part `(see the previous step for details)` here:

> ... a connection {here}, ...

Please.
___
*[templates/examples/R/body.tmpl, line 96 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGRV82ovpX0U3E-Bi:-Mnf0x8M7dv4Hdv967qd:b-rzesde) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L96)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, that's right.
</blockquote></details>

**Topic**: consistency.

I'm waiting for your comments. :thinking:

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGf7YDHzYNRiNVuAu:-Mnf1ToRBsjcnnLcjcUQ:bj1gk44) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add this part `(see the previous step for details)` here:

> ... a connection {here}, ...

Please.
</blockquote></details>

Ahh ... I thought you wanted me to see the previous step for details of what you meant ...
___
*[templates/examples/R/body.tmpl, line 96 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGRV82ovpX0U3E-Bi:-Mnf5b5D6d-yVFsZ6kIy:b-c4jrfz) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L96)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Topic**: consistency.

I'm waiting for your comments. :thinking: 
</blockquote></details>

Broken are better visible and readible.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 92 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGf7YDHzYNRiNVuAu:-MnfAz2L6KvaQERkWqfk:bb6un1j) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ahh ... I thought you wanted me to see the previous step for details of what you meant ...
</blockquote></details>

Done

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[templates/examples/R/body.tmpl, line 96 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGRV82ovpX0U3E-Bi:-MnfPGRC43r-R6KvKk2K:b85hwyp) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L96)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Broken are better visible and readible.
</blockquote></details>

Maybe unify all in a separate PR?

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 96 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-MneGRV82ovpX0U3E-Bi:-MnfQZfu9WnfURB9s3ck:b-8fx2u7) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/dbf122293aec7df3d1319331aafb7fa8a6767ddf/templates/examples/R/body.tmpl#L96)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe unify all in a separate PR?
</blockquote></details>

:+1:

**Review by janekmi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/16#-:-MnfQdsN2sd4gHyGv0us:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Pull request merged**
