### PR TITLE
example R: summary

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 122 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_A8asAwj0n8NqrY1U:-Mn_A8asAwj0n8NqrY1V:brrnxvf) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L122)):*
> ```
> forged
> ```

?

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by Patryk717 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-:-Mn_EWaZ7l6NOcqfEQfT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-:-Mn_Hc7z0YbRq3n9CFCB:bg7igk9)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 102 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_MDPn9QQ7UbtOAqR-:-Mn_MDPn9QQ7UbtOAqR0:bjqyqkx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L102)):*
> ```
> wrote
> ```

written

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 102 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_MDPn9QQ7UbtOAqR-:-Mn_OV_-0AFEV3QXZ8qH:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> wrote
> ```

written
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 122 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_A8asAwj0n8NqrY1U:-Mn_O4kb9guxDXDs9fqi:b-48fppe) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L122)):*
> formed by pressing or hammering with or without heat

:wink: 

Ref: https://www.merriam-webster.com/dictionary/forged

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 99 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_NAP4CnkSiccc8RjD:-Mn_NAP4CnkSiccc8RjE:bqzs0wg) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L99)):*
> ```
> basic
> ```

the basic
___
*[templates/examples/R/body.tmpl, line 102 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_NKg98qtsBlfNz8Ez:-Mn_NKg98qtsBlfNz8F-:be0or68) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L102)):*
> ```
> RPMem's content
> ```

the RPMem's content
___
*[templates/examples/R/body.tmpl, line 112 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_O7wfD-xBFvWtrfgw:-Mn_O7wfD-xBFvWtrfgx:b-53svsa) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L112)):*
> ```
> on the remote system
> ```

`in a remote system` - like above
___
*[templates/examples/R/body.tmpl, line 116 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_PO9x-ib2DlBotqdS:-Mn_PO9x-ib2DlBotqdT:b-icly40) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L116)):*
> ```
> The librpma 
> ```

`the librpma ...` - like in the previous sentences
___
*[templates/examples/R/body.tmpl, line 116 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_Pen294t5qrN1iRmV:-Mn_Pen294t5qrN1iRmW:by0tvhc) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L116)):*
> ```
>  ready to use
> ```

`ready-to-use` ?
___
*[templates/examples/R/body.tmpl, line 122 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_A8asAwj0n8NqrY1U:-Mn_Pxjw9zJnSOuDPLSS:bhar8uo) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> formed by pressing or hammering with or without heat

:wink: 

Ref: https://www.merriam-webster.com/dictionary/forged
</blockquote></details>

Wow :-)
___
*[templates/examples/R/body.tmpl, line 124 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_Q4smBCsagKTT0nJW:-Mn_Q4smBCsagKTT0nJX:basfhtk) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/48f4e41f96748c05577d2de4b1e7e3626c0fd646/templates/examples/R/body.tmpl#L124)):*
> ```
> allows
> ```

allow
___
*[templates/examples/R/body.tmpl, line 124 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_QAs75FWaai4O6Sv5:-Mn_QAs75FWaai4O6Sv6:b-9kiycw) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/48f4e41f96748c05577d2de4b1e7e3626c0fd646/templates/examples/R/body.tmpl#L124)):*
> ```
> learn about other supported use-cases
> ```

`learn other supported use-cases` (without about)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[templates/examples/R/body.tmpl, line 99 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_NAP4CnkSiccc8RjD:-Mn_dlNjE_LxZEI7fLBg:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> basic
> ```

the basic
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 102 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_NKg98qtsBlfNz8Ez:-Mn_do_v8vRNUXIFuTdP:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMem's content
> ```

the RPMem's content
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 112 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_O7wfD-xBFvWtrfgw:-Mn_fEUP09t-18FPsjtW:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> on the remote system
> ```

`in a remote system` - like above
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 116 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_Pen294t5qrN1iRmV:-Mn_eg-j7cZ6FgIAI6uf:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  ready to use
> ```

`ready-to-use` ?
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 116 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_PO9x-ib2DlBotqdS:-Mn_ezPN18hFpxsxlmSo:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/01b36928f575d5decd27259c683786e8afff7e49/templates/examples/R/body.tmpl#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The librpma 
> ```

`the librpma ...` - like in the previous sentences
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 124 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_Q4smBCsagKTT0nJW:-Mn_elMyEWfWvNMokubU:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/48f4e41f96748c05577d2de4b1e7e3626c0fd646/templates/examples/R/body.tmpl#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> allows
> ```

allow
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 124 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-Mn_QAs75FWaai4O6Sv5:-Mn_epN65eoduaEpySaj:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/48f4e41f96748c05577d2de4b1e7e3626c0fd646/templates/examples/R/body.tmpl#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> learn about other supported use-cases
> ```

`learn other supported use-cases` (without about)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-:-Mn_oKRf7RWqowOXpp9Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14#-:-Mna9sWR-ml3FDy1msN9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
