### PR TITLE
example R: add missing rping(1) link

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-:-Mo2fDld1_hM3tVHmTIq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 85 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2pCkH2d29lZGAN4JP:-Mo2pCkH2d29lZGAN4JQ:b-cw8o7l) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5989b789b292bce503593d8fd377e720d6053d12/templates/examples/R/body.tmpl#L85)):*
> ```
> 
> <p>
> The rping(1) command establishes a reliable RDMA connection between two nodes using
> ```

`(1)` delete?
___
*[templates/examples/R/body.tmpl, line 87 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2pB3x7mDdV3N04MKw:-Mo2oxs4C6gG6JMiQJna:bimeh24) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5989b789b292bce503593d8fd377e720d6053d12/templates/examples/R/body.tmpl#L87)):*
> ```
> The rping(1) command establishes a reliable RDMA connection between two nodes using
> librdmacm and optionally performs RDMA transfers between the nodes, then disconnects.
> When rping works, we know that the RDMA connection is correctly configured and works well.
> ```

I think this addition fits better at the end of this paragraph.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 85 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2pCkH2d29lZGAN4JP:-Mo2r_kP90vaQU5HmHmd:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5989b789b292bce503593d8fd377e720d6053d12/templates/examples/R/body.tmpl#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`(1)` delete?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[templates/examples/R/body.tmpl, line 81 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2v5QQ17H2UJLORemY:-Mo2v5QQ17H2UJLORemZ:b-6mmuet) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/8eda013b53195e3a9ef962fa0bf2e40addfc8710/templates/examples/R/body.tmpl#L81)):*
> ```
> The rping command establishes a reliable RDMA connection between two nodes using
> librdmacm and optionally performs RDMA transfers between the nodes, then disconnects.
> When rping works, we know that the RDMA connection is correctly configured and works well (see the <a href="https://linux.die.net/man/1/rping" target="_blank">rping(1)</a>
> ```

This line looks too long.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 81 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2v5QQ17H2UJLORemY:-Mo2vuKH0orftbHIqbYs:b-tpf0nz) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/8eda013b53195e3a9ef962fa0bf2e40addfc8710/templates/examples/R/body.tmpl#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line looks too long.
</blockquote></details>

We use max 90 characters here with the exception: do not break <a href> ... </a> links.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 81 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2v5QQ17H2UJLORemY:-Mo2wHYL2q62xjpotZKh:bu34voz) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/8eda013b53195e3a9ef962fa0bf2e40addfc8710/templates/examples/R/body.tmpl#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use max 90 characters here with the exception: do not break <a href> ... </a> links.
</blockquote></details>

... do not break  `<a href> ... </a>`  links.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 81 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-Mo2v5QQ17H2UJLORemY:-Mo2wc-3DUBWrDw8sb2G:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/8eda013b53195e3a9ef962fa0bf2e40addfc8710/templates/examples/R/body.tmpl#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... do not break  `<a href> ... </a>`  links.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24#-:-Mo3-1N52YPmSxuCckbl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
