### PR TITLE
docker: add script for restarting the hackathon WWW server

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[`scripts/start-hackathon.sh` line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCk0e9Z-XpvzssbNh:-NBBCk0e9Z-XpvzssbNi:b-p6fzhz) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L7)):*
> ```Shell
> DEVDAX=/dev/dax0.0
> FSDAX_MOUNT_POINT=/mnt/pmem
> HACKATHON_DIR=/home/hackathon
> ```

shouldn't it be "/home/USERNAME/hackathon" ?



_Code quote:_
```Shell
HACKATHON_DIR=/home/hackathon
```
___
*[`scripts/start-hackathon.sh` line 40 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCGbPDM7jxANkJJW-:-NBBCGbQ1XOlB16sXTH3:b-6lakda) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L40)):*
> ```Shell
> # update $HACKATHON_DIR/templates/examples/
> rm -rf $HACKATHON_DIR/templates/examples/
> /bin/cp -r ./templates/examples/ $HACKATHON_DIR/templates/
> ```

if you are in the scripts dir, shouldn't you use to dots to go one dir up? 
../templates/examples/



_Code quote:_
```Shell
./templates/examples/
```
___
*[`scripts/start-hackathon.sh` line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCSQ89d__w3p3vsb6:-NBBCSQ89d__w3p3vsb7:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L44)):*
> ```Shell
> # update $HACKATHON_DIR/img/examples/
> rm -rf $HACKATHON_DIR/img/examples/
> /bin/cp -r ./img/examples/ $HACKATHON_DIR/img/
> ```

.



_Code quote:_
```Shell
./img/examples/
```
___
*[`scripts/start-hackathon.sh` line 47 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCUDj-IPKeupYZk8O:-NBBCUDj-IPKeupYZk8P:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L47)):*
> ```Shell
> 
> # rebuild the docker image
> docker build -t pmemhackathon/pmemfc30:09 -f ./docker/Dockerfile ./docker/
> ```

.



_Code quote:_
```Shell
./docker/Dockerfile ./docker/
```
___
*[`scripts/start-hackathon.sh` line 50 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCZuU-C9O203zsIdz:-NBBCZuU-C9O203zsIe-:by0p29p) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L50)):*
> ```Shell
> 
> # re-create the users
> echo -e "y\ny\ny\n" | ./scripts/delete_pmemusers > /dev/null 2>&1
> ```

. or just ./delete_pmemusers ?



_Code quote:_
```Shell
./scripts/delete_pmemusers
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`scripts/start-hackathon.sh` line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCk0e9Z-XpvzssbNh:-NBBbRwm3fkqDGOYBYC6:b-j6grad) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L7)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

shouldn't it be "/home/USERNAME/hackathon" ?
</blockquote></details>

No, see the `create_hackathon_account` script.
___
*[`scripts/start-hackathon.sh` line 40 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCGbPDM7jxANkJJW-:-NBBbY6FBQiJpVfue4Yl:bpuxmsp) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L40)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

if you are in the scripts dir, shouldn't you use to dots to go one dir up? 
../templates/examples/
</blockquote></details>

I was in the main directory of the repo ;-)
You are right.

Done.
___
*[`scripts/start-hackathon.sh` line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCSQ89d__w3p3vsb6:-NBBbgdzCSdL-3t440p5:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L44)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`scripts/start-hackathon.sh` line 47 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCUDj-IPKeupYZk8O:-NBBbhaq-qyhQSOIDgY9:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L47)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`scripts/start-hackathon.sh` line 50 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/31#-NBBCZuU-C9O203zsIdz:-NBBbihm9KHMjgI9x2cn:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/57559d5fc2e9385ad2d1c1f965ce25768d50502d/scripts/start-hackathon.sh#L50)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

. or just ./delete_pmemusers ?
</blockquote></details>

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
