### PR TITLE
example R: set and export to docker PMEMUSER_ID

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/7)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/7)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[scripts/enable_pmemusers, line 112 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/7#-Mklq3eO0YZAaUd9W8eP:-Mklq3eO0YZAaUd9W8eQ:b-xvbhh1) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5eab5555f00371b4a06a153043de2edd545e2235/scripts/enable_pmemusers#L112)):*
> ```
> 	runy("echo 'enable_pmemusers: RPMA_SOFT_ROCE_IP=$ip'");
> 	runy("echo 'enable_pmemusers: PMEMUSER_ID=$id'");
> 	runy("docker run -t -d --name=$user --privileged --network host --env RPMA_SOFT_ROCE_IP=$ip --env PMEMUSER_ID=$id -v /dev/infiniband:/dev/infiniband -v /sys/class/infiniband:/sys/class/infiniband -v /sys/class/infiniband_verbs:/sys/class/infiniband_verbs -v /sys/class/misc/rdma_cm:/sys/class/misc/rdma_cm -v $H/users/$user/shadow:/etc/shadow -v $H/users/$user/passwd:/etc/passwd -v $H/users/$user/group:/etc/group -v $H/users/$user/home:/home/$user -v $pmemdir:/pmem -u $thisid:$thisid --hostname=container$id --workdir=/home/$user --cap-add SYS_PTRACE --restart=unless-stopped $Image");
> ```

Wouldn't be nicer to export just the effective port number we dedicate for the use of the given user?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/7)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[scripts/enable_pmemusers, line 112 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/7#-Mklq3eO0YZAaUd9W8eP:-MklrPzR2HaYtnxBa0rq:bl3nwcv) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/5eab5555f00371b4a06a153043de2edd545e2235/scripts/enable_pmemusers#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Wouldn't be nicer to export just the effective port number we dedicate for the use of the given user?
</blockquote></details>

I don't think so.
See: https://github.com/ldorau/2021-04-21/pull/21

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/7#-:-Mkpfl4218XnwRI-48hH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/7#-:-MlFwU9sCAvwsYtJQTLx:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/7#-:-MlP3xYN9582q17QXsXI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
