### PR TITLE
example R: replace connection.h with common.h

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-:-Mo3unWXE4Gobh_Fx9wa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-:-Mo40PbYDtu7aRljQdWs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo42GRv-m7N04Kzp-w5:-Mo42GRv-m7N04Kzp-w6:br7mt1x) (no related file):*
Please fix the date of this commit (Thu Aug 13 02:00:26 2020 -0400)

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo42GRv-m7N04Kzp-w5:-Mo45x7tAqhQoCaOSJKu:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix the date of this commit (Thu Aug 13 02:00:26 2020 -0400)
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo42GRv-m7N04Kzp-w5:-Mo468rsEQ5F3j1-Wmp9:bxbfaje) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see below

---
___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo467n6EthNHOIvyZuD):*
> ```
> on 8/13/2020 at 8:00 AM:
> ```

???

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo42GRv-m7N04Kzp-w5:-Mo49wed19ofuZvnAeID:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, see below
</blockquote></details>

Done.

---
___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo467n6EthNHOIvyZuD):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> on 8/13/2020 at 8:00 AM:
> ```

???
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/28#-Mo467n6EthNHOIvyZuD):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It is bug in Reviewable. Th date is OK on GitHub.

**Pull request merged**
