### PR TITLE
example R: add devdax support

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[scripts/enable_pmemusers, line 114 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlOocFXECpO_eIJFxfS:-MlOocFXECpO_eIJFxfT:b-7tuvs7) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/67e73d8dd44de650c62b49f4b14156a27e046b3f/scripts/enable_pmemusers#L114)):*
> ```
> 	runy("echo 'enable_pmemusers: PMEMUSER_ID=$id'");
> 	runy("echo 'enable_pmemusers: DEV_DAX=$dev_dax'");
> 	runy("docker run -t -d --name=$user --network host --env RPMA_SOFT_ROCE_IP=$ip --env PMEMUSER_ID=$id --env DEV_DAX=$dev_dax --device /dev/infiniband:/dev/infiniband --device /dev/dax0.0 -v /sys/class/infiniband:/sys/class/infiniband -v /sys/class/infiniband_verbs:/sys/class/infiniband_verbs -v /sys/class/misc/rdma_cm:/sys/class/misc/rdma_cm -v $H/users/$user/shadow:/etc/shadow -v $H/users/$user/passwd:/etc/passwd -v $H/users/$user/group:/etc/group -v $H/users/$user/home:/home/$user -v $pmemdir:/pmem -u $thisid:$thisid --hostname=container$id --workdir=/home/$user --cap-add SYS_PTRACE --restart=unless-stopped $Image");
> ```

Since it will be /dev/dax0.0 no matter what, why do we even need the `DEV_DAX` variable?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[scripts/enable_pmemusers, line 114 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlOoynCAnsFav42aNZQ:-MlOoynCAnsFav42aNZR:b-dcci0v) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/67e73d8dd44de650c62b49f4b14156a27e046b3f/scripts/enable_pmemusers#L114)):*
> ```
> 	runy("echo 'enable_pmemusers: PMEMUSER_ID=$id'");
> 	runy("echo 'enable_pmemusers: DEV_DAX=$dev_dax'");
> 	runy("docker run -t -d --name=$user --network host --env RPMA_SOFT_ROCE_IP=$ip --env PMEMUSER_ID=$id --env DEV_DAX=$dev_dax --device /dev/infiniband:/dev/infiniband --device /dev/dax0.0 -v /sys/class/infiniband:/sys/class/infiniband -v /sys/class/infiniband_verbs:/sys/class/infiniband_verbs -v /sys/class/misc/rdma_cm:/sys/class/misc/rdma_cm -v $H/users/$user/shadow:/etc/shadow -v $H/users/$user/passwd:/etc/passwd -v $H/users/$user/group:/etc/group -v $H/users/$user/home:/home/$user -v $pmemdir:/pmem -u $thisid:$thisid --hostname=container$id --workdir=/home/$user --cap-add SYS_PTRACE --restart=unless-stopped $Image");
> ```

I have just realized the SoftRoCE part can be simplified a little.

```
--device /dev/infiniband
```

;-)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[scripts/enable_pmemusers, line 114 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlOpZbdB_zeA63l4HUX:-MlOpZbdB_zeA63l4HUY:b-igifka) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/67e73d8dd44de650c62b49f4b14156a27e046b3f/scripts/enable_pmemusers#L114)):*
> ```
> /dev/dax0.0
> ```
$dev_dax

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[scripts/enable_pmemusers, line 114 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlOocFXECpO_eIJFxfS:-MlOy03t06kLCiNJm5MA:b61mqj8) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/67e73d8dd44de650c62b49f4b14156a27e046b3f/scripts/enable_pmemusers#L114)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it will be /dev/dax0.0 no matter what, why do we even need the `DEV_DAX` variable?
</blockquote></details>

It should be able to be set in this script, just like fsdax paths:
```
my @pmem_mounts = ('/pmem0', '/pmem1');
my $dev_dax = '/dev/dax0.0';
```
___
*[scripts/enable_pmemusers, line 114 at r2](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlOpZbdB_zeA63l4HUX:-MlOz0qUB3AgyjN8t8ma:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/67e73d8dd44de650c62b49f4b14156a27e046b3f/scripts/enable_pmemusers#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> /dev/dax0.0
> ```
$dev_dax
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-:-MlP1Bg93f316FQ5E2Gh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-:-MlPAQcV0nnQO8_NyGv6:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlPATmRAoKvkizsCmDa:-MlPATmRAoKvkizsCmDb:bns4my9) (no related file):*
Shall we have any mechanism checking the size of dax vs the number of users?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlPATmRAoKvkizsCmDa:-MlPFEkfEYaxyQRycvK8:b-14j7up) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we have any mechanism checking the size of dax vs the number of users?
</blockquote></details>

There already is:
```
#define KILOBYTE	1024
#define MAX_USERS	200
#define PMEM_MIN_SIZE	(MAX_USERS * 4 * KILOBYTE) /* 4KiB for each user */

	/* check if PMem has minimum required size */
	if (pmem_size < PMEM_MIN_SIZE) {
		(void) fprintf(stderr, "%s too small (%zu < %u)\n",
				path, pmem_size, PMEM_MIN_SIZE);
		(void) pmem_unmap(pmem_ptr, pmem_size);
		return -1;
	}
```

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlPATmRAoKvkizsCmDa:-MlPGoiV-ghWwXJ2O_Dp:bxwcjvw) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There already is:
```
#define KILOBYTE	1024
#define MAX_USERS	200
#define PMEM_MIN_SIZE	(MAX_USERS * 4 * KILOBYTE) /* 4KiB for each user */

	/* check if PMem has minimum required size */
	if (pmem_size < PMEM_MIN_SIZE) {
		(void) fprintf(stderr, "%s too small (%zu < %u)\n",
				path, pmem_size, PMEM_MIN_SIZE);
		(void) pmem_unmap(pmem_ptr, pmem_size);
		return -1;
	}
```

</blockquote></details>

but his is inside the container, I guess, but I think about something before we run all containers.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlPATmRAoKvkizsCmDa:-MlPHTGsE8xRW-BOgGWC:bx2u6yj) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but his is inside the container, I guess, but I think about something before we run all containers.
</blockquote></details>

but who creates DAX device smaller than 800 kB ???

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlPATmRAoKvkizsCmDa:-MlPXSQQ5MOWxWuY2W-M:bflcem9) (no related file):*
> but who creates DAX device smaller than 800 kB ???
I do not know, but perhaps we should add at least comment that "expected Dax device size shall be not smaller than 800k"

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-MlPATmRAoKvkizsCmDa:-MlP_pTZBlQEqJ1G7osQ:b-ikxav9) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> but who creates DAX device smaller than 800 kB ???
I do not know, but perhaps we should add at least comment that "expected Dax device size shall be not smaller than 800k"
</blockquote></details>

A comment added

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/9#-:-MlPae1P2drubKwNN280:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
